[platformio]
boards_dir = boards
default_envs = proton_ics43434_test

[env:proton_ics43434_test]
platform = https://github.com/norandomtechie/platform-raspberrypi.git#feature/proton-picosdk-support
board = proton
framework = picosdk
upload_protocol = picoprobe
monitor_speed = 115200
extra_scripts =
    pre:enable_usb_cdc.py
    post:post_upload_reset.py
build_src_flags = -O2
build_flags =
    -DPIO_NO_STDIO_UART
